version: 0.0
os: linux
# Copy war file to /opt/tomcat/webapps
files: 
  - source: /
    destination: /opt/tomcat/webapps
    overwrite: true

permissions: 
  - object: / 
    pattern: "**" 
    mode: 755
    owner: tomcat 
    group: tomcat
    
hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: afterinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 20
      runas: root
  ApplicationStop:
    - location: stop.sh
      timeout: 20
      runas: root
